### PR TITLE
Migrate project to new format

### PR DESCRIPTION
**Pull request by lawsie**

### CODE REVIEW

**Comment by JaninaPi** [comment]
In step 9, lines 30 to 39: they might make more sense in the previous step, as that's where the colour clue is set up first.

**Comment by JaninaPi** [comment]
The first mention that a GPS USB device is necessary is in step 15. Should be added to step 2, no?
"GPS USB device such as [this one](https://www.amazon.co.uk/Diymall-G-mouse-Glonass-Raspberry-Aviation/dp/B015E2XSSO)"
It could say that the device is optional, and then mention in step 15 that the learner can go to the final step if they don't have one?

**Comment by JaninaPi** [comment]
Step 16 begins with "If you have followed the instructions, you should have a copy of the piGPS library installed and tested."
The instructions in step 2 say how to install the library, but not how to test it, so something might need to be added there?

**Comment by JaninaPi** [comment]
Step 17 contained a hint about rounding numbers. I deleted that and added a link to the ingredient instead.

**Comment by JaninaPi** [comment]
There's this hint in steo 17, line 83: "You also need to check whether `last_distance = 999999`. If it is, then it should be ignored, so that the user isn't told they have got closer just because a GPS lock has been achieved."
I think it needs to be reworded and maybe moved up in the order of hints, because where/as it is, it's confusing.

**Comment by lawsie** [comment]
> In step 9, lines 30 to 39: they might make more sense in the previous step, as that's where the colour clue is set up first.

I just looked at this and I don't think we can move it - it only makes sense once there is a while loop in place, and to be able to explain that in the previous step would mean making that a lot longer.

> The first mention that a GPS USB device is necessary is in step 15. Should be added to step 2, no?
> "GPS USB device such as this one"

Added

> It could say that the device is optional, and then mention in step 15 that the learner can go to the final step if they don't have one?

Added

> Step 16 begins with "If you have followed the instructions, you should have a copy of the piGPS library installed and tested."
> The instructions in step 2 say how to install the library, but not how to test it, so something might need to be added there?

Did you change this bit already? It only says installed. Not sure what you're supposed to do to test it so let's pretend that didn't happen.

> Step 17 contained a hint about rounding numbers. I deleted that and added a link to the ingredient instead.

Cool. I've changed it though because the name of the repo was wrong

> There's this hint in steo 17, line 83: "You also need to check whether last_distance = 999999. If it is, then it should be ignored, so that the user isn't told they have got closer just because a GPS lock has been achieved."
> I think it needs to be reworded and maybe moved up in the order of hints, because where/as it is, it's confusing.

Moved into the normal text and reworded slightly

**Comment by JaninaPi** [comment]
> I just looked at this and I don't think we can move it - it only makes sense once there is a while loop in place, and to be able to explain that in the previous step would mean making that a lot longer.

OK, makes sense.

> Did you change this bit already? It only says installed.

Yes, I copy-pasted from the unedited version, bit confusing, sorry.

> Cool. I've changed it though because the name of the repo was wrong

I deleted the ingredient in the end, because I noticed it was already in the `Convert orientation to an angle` step.

> Moved into the normal text and reworded slightly

I've reworded some more, because I found the expression 'GPS lock' confusing in this context. Could you check whether it makes sense?

**Comment by lawsie** [comment]
That sounds good (step 17 GPS hint)

**Pull request merged**
